[project]
name = "httpie-websockets"
version = "0.0.1"
description = "Websocket plugin for httpie"
authors = [
    { name = "belingud", email = "1170202353@qq.com" }
]
dependencies = [
    "websockets>=12.0",
    "requests>=2.31.0",
    "httpie>=3.2.3",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
[tool.pdm]
distribution = true

[tool.pdm.build]
excludes = ["tests", ".idea/", ".vscode", ".venv", "pdm.lock", ".gitignore", "var"]
includes = ["httpie_websockets.py"]

[tool.pdm.dev-dependencies]
dev = [
    "bump2version>=1.0.1",
]

[project.entry-points."httpie.plugins.transport.v1"]
httpie_websockets = "httpie_websockets:WebsocketSPlugin"
httpie_websocket = "httpie_websockets:WebsocketPlugin"

